<?php
declare(strict_types=1);
require __DIR__ . '/src/bootstrap.php';
$flash = takeFlash();

if (!user()):
?>
<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SHOPPINGLIST V4.2 – Login</title><link rel="icon" type="image/png" sizes="64x64" href="assets/shoppinglist-favicon-64.png"><link rel="stylesheet" href="assets/app.css"><link rel="stylesheet" href="assets/shopping-view.css"></head>
<body class="login-page"><main class="login-card"><div class="brand"><img src="assets/shoppinglist-logo-256.png" alt="">SHOPPING<span>LIST</span></div><h1>Anmelden</h1><p class="muted">Schön, dass du wieder da bist.</p>
<?php if ($flash): ?><div class="flash <?= e($flash['type']) ?>"><?= e($flash['message']) ?></div><?php endif; ?>
<form method="post" action="action.php" class="form-stack"><input type="hidden" name="csrf" value="<?= e(csrfToken()) ?>"><input type="hidden" name="action" value="login"><label>Benutzername<input name="name" autocomplete="username" required autofocus></label><label>Passwort<input type="password" name="password" autocomplete="current-password" required></label><button class="primary">Login</button></form></main></body></html>
<?php exit; endif;

$allowedTabs = isAdmin() ? ['sections','locations','articles','shopping','buy'] : ['articles','shopping','buy'];
$tab = in_array($_GET['tab'] ?? '', $allowedTabs, true) ? $_GET['tab'] : 'shopping';
$sections = db()->query('SELECT * FROM SECTION ORDER BY ORDER_NR, NAME')->fetchAll();
$locations = db()->query('SELECT * FROM HOME_LOCATION ORDER BY ORDER_NR, NAME')->fetchAll();
$sortMap = ['name'=>'a.NAME','section'=>'s.NAME','location'=>'h.NAME'];
$sort = array_key_exists($_GET['sort'] ?? '', $sortMap) ? $_GET['sort'] : 'name';
$dir = ($_GET['dir'] ?? '') === 'desc' ? 'DESC' : 'ASC';
$articles = db()->query('SELECT a.*, s.NAME SECTION_NAME, h.NAME LOCATION_NAME FROM ARTICLE a JOIN SECTION s ON s.ID=a.SECTION_ID JOIN HOME_LOCATION h ON h.ID=a.HOME_LOCATION_ID ORDER BY ' . $sortMap[$sort] . ' ' . $dir . ', a.NAME')->fetchAll();
$shoppingStmt = db()->prepare('SELECT a.ID, a.NAME, a.RESERVE, h.NAME LOCATION_NAME, COALESCE(x.`COUNT`,0) QTY FROM ARTICLE a JOIN HOME_LOCATION h ON h.ID=a.HOME_LOCATION_ID LEFT JOIN ARTICLE_TO_SHOP x ON x.ARTICLE_ID=a.ID AND x.USER_ID=? ORDER BY h.ORDER_NR,h.NAME,a.NAME');
$shoppingStmt->execute([user()['id']]); $shopping = $shoppingStmt->fetchAll();
$adhocStmt = db()->prepare('SELECT ADHOC FROM `USER` WHERE ID = ?');
$adhocStmt->execute([user()['id']]); $adhoc = (string) $adhocStmt->fetchColumn();
$adhocLines = preg_split('/\R/u', $adhoc);
$hasAdhocLines = count(array_filter($adhocLines, static fn($line) => trim($line) !== '')) > 0;
$buyStmt = db()->prepare('SELECT a.ID,a.NAME,s.NAME SECTION_NAME,x.`COUNT` FROM ARTICLE_TO_SHOP x JOIN ARTICLE a ON a.ID=x.ARTICLE_ID JOIN SECTION s ON s.ID=a.SECTION_ID WHERE x.USER_ID=? AND x.`COUNT`>0 ORDER BY s.ORDER_NR,s.NAME,a.NAME');
$buyStmt->execute([user()['id']]); $buy = $buyStmt->fetchAll();
function nextSort(string $column, string $current, string $dir): string { return $column === $current && $dir === 'ASC' ? 'desc' : 'asc'; }
?>
<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SHOPPINGLIST V4.2</title><link rel="icon" type="image/png" sizes="64x64" href="assets/shoppinglist-favicon-64.png"><link rel="stylesheet" href="assets/app.css"><link rel="stylesheet" href="assets/article-fixes.css"><link rel="stylesheet" href="assets/shopping-view.css"><script defer src="assets/app.js"></script></head><body>
<header><div class="brand"><img src="assets/shoppinglist-logo-256.png" alt="">SHOPPING<span>LIST</span></div><div class="user-chip"><?= e(user()['name']) ?><?= isAdmin() ? ' · Admin' : '' ?><form method="post" action="action.php"><input type="hidden" name="csrf" value="<?= e(csrfToken()) ?>"><input type="hidden" name="action" value="logout"><button class="link">Abmelden</button></form></div></header>
<nav class="tabs">
<a class="<?= $tab==='shopping'?'active':'' ?>" href="?tab=shopping">Einkaufsliste pflegen</a><a class="<?= $tab==='buy'?'active':'' ?>" href="?tab=buy">Einkaufen</a><?php if (isAdmin()): ?><a class="<?= $tab==='sections'?'active':'' ?>" href="?tab=sections">Bereiche (Einkaufszentrum)</a><a class="<?= $tab==='locations'?'active':'' ?>" href="?tab=locations">Orte (Zu Hause)</a><?php endif; ?>
<a class="<?= $tab==='articles'?'active':'' ?>" href="?tab=articles">Artikel</a></nav>
<main class="app-main"><?php if ($flash): ?><div class="flash <?= e($flash['type']) ?>"><?= e($flash['message']) ?></div><?php endif; ?>

<?php if ($tab === 'sections' || $tab === 'locations'): $isSection=$tab==='sections'; $rows=$isSection?$sections:$locations; ?>
<section><h1><?= $isSection?'Bereiche (Einkaufszentrum)':'Orte (Zu Hause)' ?></h1><p class="muted">Eintrag auswählen, bearbeiten oder in der Reihenfolge verschieben.</p>
<form method="post" action="action.php" class="editor" data-selection-form><input type="hidden" name="csrf" value="<?= e(csrfToken()) ?>"><input type="hidden" name="tab" value="<?= e($tab) ?>"><input type="hidden" name="kind" value="<?= $isSection?'section':'location' ?>"><input type="hidden" name="id" value=""><label>Bezeichnung<input name="name" required></label><div class="button-row"><button name="action" value="lookup_add" class="primary">Hinzufügen</button><button name="action" value="lookup_update">Ändern</button><button name="action" value="lookup_delete" class="danger" data-confirm="Eintrag wirklich löschen? Zugeordnete Artikel werden ebenfalls gelöscht.">Löschen</button><button name="action" value="lookup_move" data-direction="up">↑ Nach oben</button><button name="action" value="lookup_move" data-direction="down">↓ Nach unten</button><input type="hidden" name="direction" value=""></div></form>
<div class="select-list"><?php $selectedId=(int)($_GET['selected']??0); foreach($rows as $r): ?><button type="button" class="select-row<?= $selectedId===(int)$r['ID']?' selected':'' ?>" data-id="<?= (int)$r['ID'] ?>" data-name="<?= e($r['NAME']) ?>"><span><?= e($r['NAME']) ?></span><small>Position <?= (int)$r['ORDER_NR'] ?></small></button><?php endforeach; ?></div></section>

<?php elseif ($tab === 'articles'): ?>
<section><h1>Artikel</h1><form method="post" action="action.php" class="editor article-editor" data-selection-form><input type="hidden" name="csrf" value="<?= e(csrfToken()) ?>"><input type="hidden" name="tab" value="articles"><input type="hidden" name="id"><label>Name<input name="name" required></label><label>Bereich<select name="section_id" required><option value="">Bitte wählen</option><?php foreach($sections as $r): ?><option value="<?= (int)$r['ID'] ?>"><?= e($r['NAME']) ?></option><?php endforeach; ?></select></label><label>Ort<select name="location_id" required><option value="">Bitte wählen</option><?php foreach($locations as $r): ?><option value="<?= (int)$r['ID'] ?>"><?= e($r['NAME']) ?></option><?php endforeach; ?></select></label><label class="check"><input type="checkbox" name="reserve"> Reserve vorhanden</label><div class="button-row"><button name="action" value="article_add" class="primary">Hinzufügen</button><button name="action" value="article_update">Ändern</button><?php if(isAdmin()): ?><button name="action" value="article_delete" class="danger" data-confirm="Artikel wirklich löschen?">Löschen</button><?php endif; ?></div></form>
<?php if(!$sections || !$locations): ?><div class="empty">Vor dem Erfassen von Artikeln müssen ein Bereich und ein Ort vorhanden sein.</div><?php endif; ?>
<div class="table-wrap"><table><thead><tr><?php foreach(['name'=>'Name','section'=>'Bereich','location'=>'Ort'] as $key=>$label): ?><th><a href="?tab=articles&amp;sort=<?= $key ?>&amp;dir=<?= nextSort($key,$sort,$dir) ?>"><?= $label ?><?= $sort===$key?($dir==='ASC'?' ↑':' ↓'):'' ?></a></th><?php endforeach; ?></tr></thead><tbody><?php foreach($articles as $a): ?><tr tabindex="0" class="select-row" data-id="<?= (int)$a['ID'] ?>" data-name="<?= e($a['NAME']) ?>" data-section_id="<?= (int)$a['SECTION_ID'] ?>" data-location_id="<?= (int)$a['HOME_LOCATION_ID'] ?>" data-reserve="<?= (int)$a['RESERVE'] ?>"><td><?= e($a['NAME']) ?><?= $a['RESERVE']?' <span class="badge">Reserve</span>':'' ?></td><td><?= e($a['SECTION_NAME']) ?></td><td><?= e($a['LOCATION_NAME']) ?></td></tr><?php endforeach; ?></tbody></table></div></section>

<?php elseif ($tab === 'shopping'): ?>
<section><h1>Einkaufsliste pflegen</h1><p class="muted">Menge zwischen 0 und 10 einstellen und anschliessend sichern.</p><form method="post" action="action.php"><input type="hidden" name="csrf" value="<?= e(csrfToken()) ?>"><div class="adhoc-editor"><h2>Ad hoc</h2><textarea name="adhoc" maxlength="255" rows="5"><?= e($adhoc) ?></textarea></div><div class="button-row view-switch" role="group" aria-label="Darstellungsart"><button type="button" class="active" data-shopping-view="location" aria-pressed="true">Nach Ort</button><button type="button" data-shopping-view="alphabetical" aria-pressed="false">Alphabetisch</button></div><div class="group-list" data-shopping-list><?php $group=''; $shoppingIndex=0; foreach($shopping as $r): if($group!==$r['LOCATION_NAME']): $group=$r['LOCATION_NAME']; ?><h2 data-location-heading><?= e($group) ?></h2><?php endif; ?><div class="shopping-row" data-name="<?= e($r['NAME']) ?>" data-original-index="<?= $shoppingIndex++ ?>"><span class="context"><?= e($r['LOCATION_NAME']) ?></span><div class="article-name"><strong><?= e($r['NAME']) ?></strong><?php if($r['RESERVE']): ?> <span class="badge">Reserve</span><?php endif; ?></div><div class="counter<?= (int)$r['QTY'] > 0 ? ' has-quantity' : '' ?>"><button type="button" data-step="-1">−</button><input readonly name="count[<?= (int)$r['ID'] ?>]" value="<?= (int)$r['QTY'] ?>"><button type="button" data-step="1">+</button></div></div><?php endforeach; ?></div><div class="button-row sticky-actions"><button name="action" value="shopping_save" class="primary">Aktuellen Zustand sichern</button><button name="action" value="shopping_reset" class="danger" data-confirm="Einkaufsliste wirklich auf null zurücksetzen?">Liste zurücksetzen</button></div></form></section>

<?php else: ?>
<section><h1>Einkaufen</h1><p class="muted">Artikel abhaken und die erledigten Einkäufe anschliessend aktualisieren.</p><label class="buy-filter"><input type="checkbox" data-hide-completed> Erledigte ausblenden</label><form method="post" action="action.php" data-buy-form><input type="hidden" name="csrf" value="<?= e(csrfToken()) ?>"><input type="hidden" name="action" value="buy_update"><div class="group-list buy-list"><?php if($hasAdhocLines): ?><h2 data-buy-heading>Ad hoc</h2><?php foreach($adhocLines as $adhocIndex=>$adhocLine): if(trim($adhocLine)==='') continue; ?><div class="buy-row" data-buy-row><span class="context">Ad hoc</span><label><input type="checkbox" name="completed_adhoc[]" value="<?= (int)$adhocIndex ?>" data-buy-completed><strong><?= e($adhocLine) ?></strong></label></div><?php endforeach; endif; $group=''; foreach($buy as $r): if($group!==$r['SECTION_NAME']): $group=$r['SECTION_NAME']; ?><h2 data-buy-heading><?= e($group) ?></h2><?php endif; ?><div class="buy-row" data-buy-row data-count="<?= (int)$r['COUNT'] ?>"><span class="context"><?= e($r['SECTION_NAME']) ?></span><label><input type="checkbox" name="completed[]" value="<?= (int)$r['ID'] ?>" data-buy-completed data-buy-qty><strong><?= e($r['NAME']) ?></strong> <span class="badge" data-buy-count-badge><?= (int)$r['COUNT'] ?>×</span></label><input type="hidden" name="count[<?= (int)$r['ID'] ?>]" value="<?= (int)$r['COUNT'] ?>" data-buy-count-input></div><?php endforeach; if(!$buy && !$hasAdhocLines): ?><div class="empty">Die Einkaufsliste ist leer.</div><?php endif; ?></div><?php if($buy || $hasAdhocLines): ?><div class="button-row sticky-actions"><button class="primary">Aktualisieren</button></div><?php endif; ?></form></section>
<?php endif; ?></main></body></html>
