-- SHOPPINGLIST database schema for MariaDB 10.x
-- Generated from "ERM-Modell fuer die SHOPPINGLIST-App", version 4.0

CREATE DATABASE IF NOT EXISTS `SHOPPINGLIST`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE `SHOPPINGLIST`;

CREATE TABLE `USER` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NOT NULL,
  `PASSWORD` VARCHAR(255) NOT NULL,
  `ADMIN` BOOLEAN NOT NULL DEFAULT FALSE,
  `ADHOC` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UQ_USER_NAME` (`NAME`)
) ENGINE=InnoDB;

CREATE TABLE `SECTION` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NOT NULL,
  `ORDER_NR` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UQ_SECTION_NAME` (`NAME`)
) ENGINE=InnoDB;

CREATE TABLE `HOME_LOCATION` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NOT NULL,
  `ORDER_NR` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UQ_HOME_LOCATION_NAME` (`NAME`)
) ENGINE=InnoDB;

CREATE TABLE `ARTICLE` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(150) NOT NULL,
  `RESERVE` BOOLEAN NOT NULL DEFAULT FALSE,
  `ORDER_NR` INT NOT NULL DEFAULT 0,
  `SECTION_ID` BIGINT UNSIGNED NOT NULL,
  `HOME_LOCATION_ID` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UQ_ARTICLE_NAME` (`NAME`),
  KEY `IX_ARTICLE_SECTION_ID` (`SECTION_ID`),
  KEY `IX_ARTICLE_HOME_LOCATION_ID` (`HOME_LOCATION_ID`),
  CONSTRAINT `FK_ARTICLE_SECTION`
    FOREIGN KEY (`SECTION_ID`) REFERENCES `SECTION` (`ID`)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT `FK_ARTICLE_HOME_LOCATION`
    FOREIGN KEY (`HOME_LOCATION_ID`) REFERENCES `HOME_LOCATION` (`ID`)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE `ARTICLE_TO_SHOP` (
  `USER_ID` BIGINT UNSIGNED NOT NULL,
  `ARTICLE_ID` BIGINT UNSIGNED NOT NULL,
  `COUNT` INT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`USER_ID`, `ARTICLE_ID`),
  KEY `IX_ARTICLE_TO_SHOP_ARTICLE_ID` (`ARTICLE_ID`),
  CONSTRAINT `FK_ARTICLE_TO_SHOP_USER`
    FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT `FK_ARTICLE_TO_SHOP_ARTICLE`
    FOREIGN KEY (`ARTICLE_ID`) REFERENCES `ARTICLE` (`ID`)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT `CK_ARTICLE_TO_SHOP_COUNT` CHECK (`COUNT` > 0)
) ENGINE=InnoDB;
